FoodDeliveryApp03/Controllers/MenuItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FoodDeliveryApp03.Data;
using FoodDeliveryApp03.Models;
using Microsoft.AspNetCore.Authorization;
using FoodDeliveryApp03.Extensions;
using System.Security.Claims;
using Microsoft.AspNetCore.Identity;

namespace FoodDeliveryApp03.Controllers
{
    public class MenuItemsController : Controller
    {
        private readonly DBContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public MenuItemsController(DBContext context , UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var menuItemsWithReviews = await _context.MenuItems
                .Include(m => m.Reviews)
                .ToListAsync();

            foreach (var menuItem in menuItemsWithReviews)
            {
                menuItem.AverageRating = menuItem.Reviews.Any()
                    ? menuItem.Reviews.Average(r => r.Rating)
                    : 0;
            }

            var sortedMenuItems = menuItemsWithReviews
                .OrderByDescending(m => m.AverageRating)
                .GroupBy(m => m.RestaurantName)
                .ToList();

            return View(sortedMenuItems);
        }


        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.MenuItems == null)
            {
                return NotFound();
            }

            var menuItem = await _context.MenuItems
                .Include(m => m.User)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (menuItem == null)
            {
                return NotFound();
            }

            return RedirectToAction("Index", "Profile", new { id = menuItem.UserId });
        }


        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(MenuItem product,IFormFile? photo)
        {

                if (product.Photo != null && product.Photo.Length > 0)
                {
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", product.Photo.FileName);
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await product.Photo.CopyToAsync(stream);
                    }

                    product.ImagePath = "/images/" + product.Photo.FileName;
                }

                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                var user = await _userManager.FindByIdAsync(userId);
                if (user is ApplicationUser applicationUser)
                {
                    product.RestaurantName = applicationUser.RestaurantName;
                    product.UserId = applicationUser.Id;
                }

            _context.Add(product);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
           
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.MenuItems == null)
            {
                return NotFound();
            }

            var menuItem = await _context.MenuItems.FindAsync(id);
            if (menuItem == null)
            {
                return NotFound();
            }
            return View(menuItem);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,RestaurantName,Description,Price,ImagePath")] MenuItem menuItem)
        {
            if (id != menuItem.Id)
            {
                return NotFound();
            }
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = await _userManager.FindByIdAsync(userId);
            if (user is ApplicationUser applicationUser)
            {
                menuItem.RestaurantName = applicationUser.RestaurantName;
            }
            

            try
                {
                    _context.Update(menuItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MenuItemExists(menuItem.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

            return RedirectToAction(nameof(Index));

        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.MenuItems == null)
            {
                return NotFound();
            }

            var menuItem = await _context.MenuItems
                .FirstOrDefaultAsync(m => m.Id == id);
            if (menuItem == null)
            {
                return NotFound();
            }

            return View(menuItem);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.MenuItems == null)
            {
                return Problem("Entity set 'DBContext.MenuItems'  is null.");
            }
            var menuItem = await _context.MenuItems.FindAsync(id);
            if (menuItem != null)
            {
                _context.MenuItems.Remove(menuItem);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Profile");
        }

        private bool MenuItemExists(int id)
        {
          return (_context.MenuItems?.Any(e => e.Id == id)).GetValueOrDefault();
        }
        public IActionResult ViewProfile(string userId)
        {
            return RedirectToAction("Profile", "Profile", new { id = userId });
        }


    }
}

FoodDeliveryApp03/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using FoodDeliveryApp03.Data;
using FoodDeliveryApp03.Models;
using Microsoft.EntityFrameworkCore;

namespace FoodDeliveryApp03.Controllers
{
    //[Authorize]
    public class ProfileController : Controller
    {
        private readonly DBContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public ProfileController(DBContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [HttpGet]
        
        public async Task<IActionResult> Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var profile = await _context.ProfilePicture.FirstOrDefaultAsync(p => p.UserId == userId);
            var menuItems = await _context.MenuItems.Where(m => m.UserId == userId).ToListAsync();

            ViewBag.Profile = profile;
            ViewBag.MenuItems = menuItems;

            return View();
        }




        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProfilePicture profilePicture, IFormFile photo)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var existingProfilePicture = await _context.ProfilePicture.FirstOrDefaultAsync(p => p.UserId == userId);

            if (existingProfilePicture != null)
            {
                _context.ProfilePicture.Remove(existingProfilePicture);
                await _context.SaveChangesAsync();
            }

            if (photo != null && photo.Length > 0)
            {
                var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", photo.FileName);

                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await photo.CopyToAsync(stream);
                }

                profilePicture.ImagePath = "/images/" + photo.FileName;
            }

            profilePicture.UserId = userId;
            var user = await _userManager.FindByIdAsync(userId);

            if (user is ApplicationUser applicationUser)
            {
                profilePicture.RestaurantName = applicationUser.RestaurantName;
            }

            _context.ProfilePicture.Add(profilePicture);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        [HttpGet]
        public async Task<IActionResult> Profile(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var profile = await _context.ProfilePicture.FirstOrDefaultAsync(p => p.UserId == id);
            if (profile == null)
            {
                return NotFound();
            }

            var menuItems = await _context.MenuItems.Where(m => m.UserId == id).ToListAsync();

            ViewBag.Profile = profile;
            ViewBag.MenuItems = menuItems;

            return View(profile); 
            }



    }
}

FoodDeliveryApp03/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;
using FoodDeliveryApp03.Models;

namespace FoodDeliveryApp03.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;

        public UserController(UserManager<IdentityUser> userManager)
        {
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            var users = _userManager.Users.ToList();
            return View(users);
        }

        public async Task<IActionResult> BanTemporary(string userId, int hours)
        {
            var user = await _userManager.FindByIdAsync(userId) as ApplicationUser ;
            if (user != null)
            {
                var banExpiration = DateTime.UtcNow.AddHours(hours);
                user.IsBanned = true;
                user.BanExpirationDate = banExpiration;
                await _userManager.UpdateAsync(user);
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> BanPermanent(string userId)
        {
            var user = await _userManager.FindByIdAsync(userId) as ApplicationUser;
            if (user != null)
            {
                user.IsBanned = true;
                user.BanExpirationDate = null; 
                await _userManager.UpdateAsync(user);
                var result = await _userManager.UpdateAsync(user);
                if (result.Succeeded)
                {
                    TempData["SuccessMessage"] = "User has been temporarily banned.";
                }
                else
                {
                    TempData["ErrorMessage"] = "Failed to ban the user.";
                }
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Unban(string userId)
        {
            var user = await _userManager.FindByIdAsync(userId) as ApplicationUser;
            if (user != null)
            {
                user.IsBanned = false;
                user.BanExpirationDate = null;
                await _userManager.UpdateAsync(user);
                var result = await _userManager.UpdateAsync(user);
                if (result.Succeeded)
                {
                    TempData["SuccessMessage"] = "User has been unbanned.";
                }
                else
                {
                    TempData["ErrorMessage"] = "Failed to unban the user.";
                }
            }
                
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(string userId)
        {
            var user = await _userManager.FindByIdAsync(userId) as ApplicationUser;
            if (user != null)
            {
                var result = await _userManager.DeleteAsync(user);
                if (!result.Succeeded)
                {
                    
                }
            }

            return RedirectToAction("Index");
        }
    }
}

FoodDeliveryApp03/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Food Delivery App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FoodDeliveryApp03.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.js"></script>

    

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow ">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FoodDeliveryApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between"> 
                    <ul class="navbar-nav flex-grow-1 mr-auto" style="display:flex !important; justify-content:flex-end !important;">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole("Restaurant-Manager"))
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Profile" asp-action="Index">Profile</a>
                        </li>
                        <li class="nav-item">
                                <a class="nav-link" asp-controller="Carts" asp-action="Dashboard">Dashboard</a>
                        </li>
                        }
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MenuItems" asp-action="Index">MenuItems</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Carts" asp-action="Index">Cart</a>
                        </li>
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
            
        </nav>
    </header>
    <div>
        <main class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer style="text-align:center;" class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - FoodDeliveryApp - Created by Ardit Shillova - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>