FoodDeliveryApp03/Models/MenuItem.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;
using System.Drawing;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion.Internal;

namespace FoodDeliveryApp03.Models
{
    public class MenuItem
    {

            [DatabaseGenerated(DatabaseGeneratedOption.Identity)] 
            public int Id { get; set; }
            public string Name { get; set; }
            public string Description { get; set; }  
            public decimal Price { get; set; }  
            public string UserId { get; set; }
            public ApplicationUser User { get; set; }
            public string RestaurantName { get; set; }
            public DateTime CreatedAt { get; set; }
            public string ImagePath { get; set; }
            [NotMapped]
            public IFormFile Photo { get; set; }
            public double AverageRating { get; set; }
            public ICollection<Review> Reviews { get; set; }
            public List<Cart> Carts { get; set; }
        
    }
}

FoodDeliveryApp03/Controllers/MenuItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FoodDeliveryApp03.Data;
using FoodDeliveryApp03.Models;
using Microsoft.AspNetCore.Authorization;
using FoodDeliveryApp03.Extensions;
using System.Security.Claims;
using Microsoft.AspNetCore.Identity;

namespace FoodDeliveryApp03.Controllers
{
    public class MenuItemsController : Controller
    {
        private readonly DBContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public MenuItemsController(DBContext context , UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var menuItemsWithReviews = await _context.MenuItems
                .Include(m => m.Reviews)
                .ToListAsync();

            foreach (var menuItem in menuItemsWithReviews)
            {
                menuItem.AverageRating = menuItem.Reviews.Any()
                    ? menuItem.Reviews.Average(r => r.Rating)
                    : 0;
            }

            var sortedMenuItems = menuItemsWithReviews
                .OrderByDescending(m => m.AverageRating)
                .GroupBy(m => m.RestaurantName)
                .ToList();

            return View(sortedMenuItems);
        }


        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.MenuItems == null)
            {
                return NotFound();
            }

            var menuItem = await _context.MenuItems
                .Include(m => m.User)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (menuItem == null)
            {
                return NotFound();
            }

            return RedirectToAction("Index", "Profile", new { id = menuItem.UserId });
        }


        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(MenuItem product,IFormFile? photo)
        {

                if (product.Photo != null && product.Photo.Length > 0)
                {
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", product.Photo.FileName);
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await product.Photo.CopyToAsync(stream);
                    }

                    product.ImagePath = "/images/" + product.Photo.FileName;
                }

                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                var user = await _userManager.FindByIdAsync(userId);
                if (user is ApplicationUser applicationUser)
                {
                    product.RestaurantName = applicationUser.RestaurantName;
                    product.UserId = applicationUser.Id;
                }

            _context.Add(product);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
           
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.MenuItems == null)
            {
                return NotFound();
            }

            var menuItem = await _context.MenuItems.FindAsync(id);
            if (menuItem == null)
            {
                return NotFound();
            }
            return View(menuItem);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,RestaurantName,Description,Price,ImagePath")] MenuItem menuItem)
        {
            if (id != menuItem.Id)
            {
                return NotFound();
            }
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = await _userManager.FindByIdAsync(userId);
            if (user is ApplicationUser applicationUser)
            {
                menuItem.RestaurantName = applicationUser.RestaurantName;
            }
            

            try
                {
                    _context.Update(menuItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MenuItemExists(menuItem.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

            return RedirectToAction(nameof(Index));

        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.MenuItems == null)
            {
                return NotFound();
            }

            var menuItem = await _context.MenuItems
                .FirstOrDefaultAsync(m => m.Id == id);
            if (menuItem == null)
            {
                return NotFound();
            }

            return View(menuItem);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.MenuItems == null)
            {
                return Problem("Entity set 'DBContext.MenuItems'  is null.");
            }
            var menuItem = await _context.MenuItems.FindAsync(id);
            if (menuItem != null)
            {
                _context.MenuItems.Remove(menuItem);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Profile");
        }

        private bool MenuItemExists(int id)
        {
          return (_context.MenuItems?.Any(e => e.Id == id)).GetValueOrDefault();
        }
        public IActionResult ViewProfile(string userId)
        {
            return RedirectToAction("Profile", "Profile", new { id = userId });
        }


    }
}

FoodDeliveryApp03/Controllers/ReviewsController.cs
using FoodDeliveryApp03.Data;
using FoodDeliveryApp03.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

[Authorize] 
public class ReviewsController : Controller
{
    private readonly DBContext _context;

    public ReviewsController(DBContext context)
    {
        _context = context;
    }

    [HttpGet]
    public IActionResult SubmitReviewForMenuItem(int menuItemId)
    {
        var menuItem = _context.MenuItems.Include(m => m.Reviews).FirstOrDefault(m => m.Id == menuItemId);
        if (menuItem == null)
        {
            return NotFound();
        }

        return View(menuItem);
    }

    [HttpPost]
    public IActionResult SubmitReviewForMenuItem(int menuItemId, int rating , string reviewText)
    {
        var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

        var menuItem = _context.MenuItems.FirstOrDefault(m => m.Id == menuItemId);
        if (menuItem == null)
        {
            return NotFound();
        }

        var review = new Review
        {
            UserId = userId,
            Rating = rating,
            MenuItemId = menuItemId,
            CreatedAt = DateTime.UtcNow 
        };

        _context.Reviews.Add(review);
        _context.SaveChanges();

        return RedirectToAction("Index", "MenuItems", new { id = menuItemId });
    }
}

FoodDeliveryApp03/Views/MenuItems/Create.cshtml
@model FoodDeliveryApp03.Models.MenuItem

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>MenuItem</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Photo"></label>
                <input asp-for="Photo" type="file" class="form-control-file" />
                <span asp-validation-for="Photo" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FoodDeliveryApp03/Views/MenuItems/Delete.cshtml
@model FoodDeliveryApp03.Models.MenuItem

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MenuItem</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImagePath)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FoodDeliveryApp03/Views/MenuItems/Details.cshtml
@model FoodDeliveryApp03.Models.MenuItem

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>MenuItem</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImagePath)
        </dd>
    </dl>
</div>
<h2>Reviews</h2>
<ul>
    @foreach (var review in Model.Reviews)
    {
        <li>
            <strong>Rating: @review.Rating</strong>
        </li>
    }
</ul>

<h3>Submit Review</h3>
<form asp-controller="Reviews" asp-action="SubmitReviewForMenuItem" method="post">
    <input type="hidden" name="menuItemId" value="@Model.Id" />
    <label>Rating: </label>
    <input type="number" name="rating" min="1" max="5" required />
    <br />
    <label>Review: </label>
    <textarea name="reviewText" rows="3" required></textarea>
    <br />
    <button type="submit">Submit Review</button>
</form>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

FoodDeliveryApp03/Views/MenuItems/Edit.cshtml
@model FoodDeliveryApp03.Models.MenuItem

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>MenuItem</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImagePath" class="control-label"></label>
                <input asp-for="ImagePath" class="form-control" />
                <span asp-validation-for="ImagePath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FoodDeliveryApp03/Views/MenuItems/Index.cshtml
@model IEnumerable<IGrouping<string, MenuItem>>
@{
    ViewData["Title"] = "Index";
}
@foreach (var group in Model)
{
    <div id="container">
        <h1 style="text-align: center;">Restaurants</h1>
        <div class="MenuItem">
        
                <h2>
                    <a href="@Url.Action("Profile", "Profile", new { id = group.First().UserId })">@group.Key</a>
                </h2>
                <div class="div3">
                        <div class="">
                            @foreach (var item in group)
                        {
                            <div class="div-hover1">
                                <div class="menu-container">
                                    <img src="@Url.Content(item.ImagePath)" alt="Profile Picture" width="200" height="200" />
                                    <div class="div-hover">
                                        <form class="form1" asp-controller="Carts" asp-action="AddToCart" method="post">
                                            <input type="hidden" name="menuItemId" value="@item.Id" />
                                            <button class="btn1" type="submit">Add to Cart</button>
                                        </form>
                                
                                    </div>

                                </div>
                                <div class="rating-system">
                                    <form asp-controller="Reviews" asp-action="SubmitReviewForMenuItem" method="post">
                                        <input type="hidden" name="menuItemId" value="@item.Id" />
                                        <div class="star-rating">
                                            <input type="radio" id="rating1" name="rating" value="1" required />
                                            <label for="rating5">&#9733;</label>
                                            <input type="radio" id="rating2" name="rating" value="2" />
                                            <label for="rating4">&#9733;</label>
                                            <input type="radio" id="rating3" name="rating" value="3" />
                                            <label for="rating3">&#9733;</label>
                                            <input type="radio" id="rating4" name="rating" value="4" />
                                            <label for="rating2">&#9733;</label>
                                            <input type="radio" id="rating5" name="rating" value="5" />
                                            <label for="rating1">&#9733;</label>
                                        </div>
                                        <button type="submit">Submit Review</button>
                                    </form>
                                </div>
                                <br/>
                                <div style="display:flex; justify-content:center; ">
                                    @if (item.Reviews != null && item.Reviews.Any())
                                    {
                                        double averageRating = item.Reviews.Average(r => r.Rating);
                                        <span class="star-rating">
                                            @for (int i = 1; i <= 5; i++)
                                            {
                                                if (i <= averageRating)
                                                {
                                                    <span>&#9733;</span>
                                                }
                                                else if (i - 0.5 <= averageRating)
                                                {
                                                    <span>&#9734;</span>
                                                }
                                                else if (i - 0.25 <= averageRating)
                                                {
                                                    <span>&#9734;</span>
                                                }
                                                else
                                                {
                                                    <span>&#9734;</span>
                                                }
                                            }
                                        </span>
                                    }
                                    else
                                    {
                                        <span class="star-rating">
                                            @for (int i = 1; i <= 5; i++)
                                            {
                                                <span>&#9734;</span>
                                            }
                                        </span>
                                    }
                                </div>

                                <h2 style="font-size: 30px; text-align: center;">@item.Name
                                    <h2 style="display:flex; justify-content:center; "><button class="rate-button" style=" ">&#9734</button></h2>
                                </h2>
                                <p style="font-size: 20px; text-align: center;">@item.Price€</p>
                            </div>
                        }
                    </div>
                </div>
        
        </div>
    </div>
}
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const showRatingButtons = document.querySelectorAll('.rate-button');
        const ratingSystems = document.querySelectorAll('.rating-system');

        showRatingButtons.forEach(function (button, index) {
            button.addEventListener('click', function () {
                const ratingSystem = ratingSystems[index];
                if (ratingSystem.style.display === 'none' || ratingSystem.style.display === '') {
                    ratingSystem.style.display = 'block';
                } else {
                    ratingSystem.style.display = 'none';
                }
            });
        });
    });
</script>